name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        docker_repo: melonc
        image_name: meproc
        tag: latest
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} 
        docker build . --file Dockerfile --tag $docker_repo/$image_name:$tag
        docker push $docker_repo/$image_name:$tag
